### ISSUE TITLE
Como developer quiero saber si dos items han colisionado

### ISSUE THREAD

**Issue by agonsant** [last-mille-112022/snake-solid-ts#4]
Necesitamos saber si dos ítems de la UI han colisionado. Dos elementos colisionan si su posición `x,y` en la interfaz coinciden en algún momento en la ejecución del juego.

Crear un motor de colisiones que nos ayude a verificar si dos elementos han colisionado.

¿Cómo diseñarías este método?
¿Cómo se integra con el resto de elementos?
¿Quién es el propietario de tenerlo como dependencia?

**Comment by davzlum** [comment]
Tendremos una función llamada checkCollision(item1, item2) donde recibiremos la posición (x,y) de los dos items y comprobaremos si coinciden. En caso de que coincidan retornaremos true.

**Comment by afabregasm** [comment]
## Option 1

```mermaid
flowchart LR

A[dev] --> B("checkCollision(coordinatesA, coordinatesB)")
B --> C{Based on}
C -->|They collide| D[true]
C -->|They don't collide| E[false]
```

Function that takes the coordenates of 2 items and checks if they collide.
How to check if they collide?

```ts
coordinatesA.x === coordinatesB.x && coordinatesA.y === coordinatesB.y
```

This method could be placed anywhere or have it's own class.

---
## Option 2

```mermaid
flowchart LR

A[dev] --> B("Coordinates.checkCollision(coordinates)")
B --> C{Based on}
C -->|They collide| D[true]
C -->|They don't collide| E[false]
```

Method inside `Coordinates` class, takes another coordinates as parameters and checks if they collide.
How to check if they collide?

```ts
this.x === coordinates.x && this.y === coordinates.y
```

### Why?
So another class doesn't need to know about `Coordinates` attributes. Also, this way we can group all methods that use coordinates in the same class and be easily reused.
