### ISSUE TITLE
Como usuario quiero ver comida que la Snake pueda comer

### ISSUE THREAD

**Issue by agonsant** [last-mille-112022/snake-solid-ts#6]
Cuando empezamos el juego empezarán a aparecer elementos que con la que la snake pueda colisionar y realizar alguna acción. 
Cada 15 segundos que desaparecen a los 20 segundos. Esta tasa de generación y desaparecer puede cambiar durante la ejecución del juego o en función de la dificultad.

Los ítems tienen un color asociado

En este caso vamos a querer crear un elemento comida. 

Este elemento al ser colisionado hará crecer la Snake en 1 unidad y añade al score 100 puntos. Tiene un color rojo asociado.

¿Cómo generarías los elementos dado estos posibles cambios o crecimiento?
¿Podrían existir nuevos elementos en un futuro?

**Comment by davzlum** [comment]
`interface generateFood {
     drawFood(coordinates: Coordinates): void,
     removeFood(): void,
     foodDuration(time: number): void,
     foodColor(color: string): void
}`
